# --- Generated

# --- !Ups
CREATE TABLE "tasks" ("id" BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,"name" VARCHAR NOT NULL,"start_time" TIME NOT NULL,"project_id" BIGINT NOT NULL);
CREATE TABLE "projects" ("id" BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,"name" VARCHAR NOT NULL);
CREATE TABLE "steps" ("id" BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,"name" VARCHAR NOT NULL,"duration" INTEGER NOT NULL,"task_id" BIGINT NOT NULL);
CREATE TABLE "resources" ("id" BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,"name" VARCHAR NOT NULL,"size" INTEGER NOT NULL,"color" INTEGER NOT NULL,"project_id" BIGINT NOT NULL)

# --- !Downs
DROP TABLE "tasks";
DROP TABLE "projects";
DROP TABLE "steps";
DROP TABLE "resources"

